--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-06-24 00:58:37

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16598)
-- Name: app_users; Type: TABLE; Schema: public; Owner: hahn
--

CREATE TABLE public.app_users (
    id bigint NOT NULL,
    password character varying(25),
    username character varying(30)
);


ALTER TABLE public.app_users OWNER TO hahn;

--
-- TOC entry 219 (class 1259 OID 16597)
-- Name: app_users_id_seq; Type: SEQUENCE; Schema: public; Owner: hahn
--

ALTER TABLE public.app_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16587)
-- Name: products; Type: TABLE; Schema: public; Owner: hahn
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    description character varying(1000),
    name character varying(25) NOT NULL,
    price double precision NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT products_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.products OWNER TO hahn;

--
-- TOC entry 217 (class 1259 OID 16586)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: hahn
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4706 (class 2606 OID 16604)
-- Name: app_users app_users_pkey; Type: CONSTRAINT; Schema: public; Owner: hahn
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);


--
-- TOC entry 4702 (class 2606 OID 16594)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: hahn
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 4704 (class 2606 OID 16596)
-- Name: products uko61fmio5yukmmiqgnxf8pnavn; Type: CONSTRAINT; Schema: public; Owner: hahn
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT uko61fmio5yukmmiqgnxf8pnavn UNIQUE (name);


--
-- TOC entry 4708 (class 2606 OID 16606)
-- Name: app_users ukspsnwr241e9k9c8p5xl4k45ih; Type: CONSTRAINT; Schema: public; Owner: hahn
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT ukspsnwr241e9k9c8p5xl4k45ih UNIQUE (username);


-- Completed on 2025-06-24 00:58:37

--
-- PostgreSQL database dump complete
--

